[functions]
[functions.generate-music]
verify_jwt = false

[functions.render-video]
verify_jwt = false

[functions.proxy-video]
verify_jwt = false

[functions.get-download-url]
verify_jwt = false

[functions.render-complete]
verify_jwt = false

[functions.create-infinitepay-link]
verify_jwt = true

[functions.infinitepay-webhook]
verify_jwt = false

[functions.check-infinitepay-payment]
verify_jwt = true
